export const helperConstants = {
  THEME_CHANGE_REQUEST: "THEME_CHANGE_REQUEST",
  MARGIN_CHANGE_REQUEST: "MARGIN_CHANGE_REQUEST",
  SEARCH_CHANGE_REQUEST: "SEARCH_CHANGE_REQUEST",
};

export const fileFolderConstants = {
  ADD_FILE_FOLDER_REQUEST: "ADD_FILE_FOLDER_REQUEST",
  DELETE_FILE_FOLDER_REQUEST: "DELETE_FILE_FOLDER_REQUEST",
  RENAME_FILE_FOLDER_REQUEST: "RENAME_FILE_FOLDER_REQUEST",
};
